
import { ChevronDown } from 'lucide-react';
import { useState } from 'react';

const faqs = [
  {
    question: "How detailed are the specifications generated by BPSpecs?",
    answer: "BPSpecs creates comprehensive specifications that include business overview, technical requirements, market analysis, financial projections, implementation roadmap, risk assessment, and more. Each specification is typically 15-25 pages of detailed, actionable content."
  },
  {
    question: "Can I edit and customize the generated content?",
    answer: "Absolutely! BPSpecs generates your specifications in editable formats. You can modify, add, or remove sections to match your specific needs. We also provide templates and suggestions for customization."
  },
  {
    question: "Is my business idea kept confidential and secure?",
    answer: "Yes, we take security seriously. All data is encrypted, we never share your business ideas with third parties, and you can delete your projects at any time. We're SOC 2 compliant and follow industry best practices for data protection."
  },
  {
    question: "What formats can I export my business specifications to?",
    answer: "You can export in multiple formats including PDF (for investors), Markdown (for developers), Word documents, and structured business plan formats. Premium plans also include custom branding options."
  },
  {
    question: "Do you offer support for complex or unique business models?",
    answer: "Yes! Our AI is trained on thousands of business models across industries. For complex businesses, our Pro and Team plans include access to business planning experts who can review and enhance your specifications."
  },
  {
    question: "How does BPSpecs compare to hiring a business consultant?",
    answer: "BPSpecs provides 80% of what a consultant would deliver in 5% of the time and cost. For complex projects, we recommend using BPSpecs as a starting point and then consulting with our expert network for refinement."
  }
];

const FAQSection = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-20 lg:py-32 bg-bpspecs-dark-charcoal">
      <div className="container mx-auto px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6 text-bpspecs-off-white leading-tight">
              Frequently Asked<br />
              <span className="text-gradient">Questions</span>
            </h2>
            <p className="text-xl text-bpspecs-beige font-medium">
              Everything you need to know about BPSpecs and business plan specifications
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div 
                key={index}
                className="bg-bpspecs-off-white rounded-lg border border-bpspecs-taupe/20 overflow-hidden"
              >
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full px-8 py-6 text-left flex items-center justify-between hover:bg-bpspecs-beige/20 transition-colors duration-200"
                >
                  <span className="text-lg font-semibold text-bpspecs-dark-charcoal pr-4">
                    {faq.question}
                  </span>
                  <ChevronDown 
                    className={`w-5 h-5 text-bpspecs-taupe transition-transform duration-200 flex-shrink-0 ${
                      openIndex === index ? 'rotate-180' : ''
                    }`}
                  />
                </button>
                {openIndex === index && (
                  <div className="px-8 pb-6">
                    <p className="text-bpspecs-taupe leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <p className="text-bpspecs-beige mb-6">
              Still have questions? Our team is here to help.
            </p>
            <button className="bg-bpspecs-teal hover:bg-bpspecs-teal/90 text-bpspecs-off-white px-8 py-3 rounded-lg font-semibold transition-all duration-200">
              Contact Support
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
